# Generated by Django 5.1.4 on 2025-01-23 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("place", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                ("reward", models.CharField(blank=True, max_length=255, null=True)),
                ("pleasant_habit", models.BooleanField(default=False)),
                ("frequency", models.IntegerField(default=1)),
                ("public", models.BooleanField(default=False)),
                ("duration", models.IntegerField(default=120)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_to",
                        to="habits.habit",
                    ),
                ),
            ],
        ),
    ]
